### ISSUE TITLE
Uncaught TypeError: item.getURI is not a function

### ISSUE THREAD

**Issue by snackattas** [junga-com/bg-atom-tree-view-toolbar#3]
[Enter steps to reproduce:]

It just happens when I boot up Atom

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.1
**Thrown From**: [bg-tree-view-toolbar](https://github.com/junga-com/bg-atom-tree-view-toolbar) package 2.0.0

### Stack Trace

Uncaught TypeError: item.getURI is not a function

```
At /Users/zattas/.atom/packages/bg-tree-view-toolbar/node_modules/bg-atom-utils/polyfill-workspace.js:86

TypeError: item.getURI is not a function
    at /packages/bg-tree-view-toolbar/node_modules/bg-atom-utils/polyfill-workspace.js:86:55
    at Array.find (<anonymous>)
    at Workspace.getItemByURI (/packages/bg-tree-view-toolbar/node_modules/bg-atom-utils/polyfill-workspace.js:86:16)
    at Workspace.itemForURI (/packages/bg-tree-view-toolbar/node_modules/bg-atom-utils/polyfill-workspace.js:82:35)
    at TreeToolbarView.getTreeView (/packages/bg-tree-view-toolbar/lib/TreeToolbarView.js:147:34)
    at TreeToolbarView.registerTooltips (/packages/bg-tree-view-toolbar/lib/TreeToolbarView.js:167:13)
    at /packages/bg-tree-view-toolbar/lib/TreeToolbarView.js:47:24
```

### Commands

```
     -0:25.8.0 core:backspace (input.hidden-input)
  5x -0:17.8.0 core:confirm (input.hidden-input)
     -0:12.6.0 core:select-all (input.hidden-input)
     -0:11.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-ide-ui 0.13.0 
bg-tree-view-toolbar 2.0.0 
bg-ui-font-sizer 2.0.0 
busy-signal 2.0.1 
file-type-icons 1.3.4 
highlight-selected 0.17.0 
intentions 2.1.1 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-jenkinsfile 0.1.1 
linter 3.4.0 
linter-jenkins 1.0.7 
linter-ui-default 3.4.1 
minimap 4.40.0 
path-copy 0.14.0 
shebang-set-grammar 0.8.0 
tree-view-copy-relative-path 1.2.0 
```

**Comment by bobjunga** [comment]
Sorry about that. I released new versions of all my projects and it turned out that they work together when installed in development mode (--dev) like I typically use them, but in production installs if more than one of my bg-* plugins are installed, they cause atom to crash.

I will release a fix to this sometime this week. In the meantime, you can uninstall all but one bg-* plugin (you seem to have bg-tree-view-toolbar and bg-ui-font-sizer installed).

From the command line you can see which are installed like with this command
`ls -ld ~/.atom/packages/bg-*`

To remove an atom plugin from the command line, remove the directory with the plugin name
`mv  ~/.atom/packages/<packageName> /tmp`
Of course you could just delete it but I did not want to have people copy and pasting a rm -rf command.

--BobG
